### ISSUE TITLE
android:attr/android:progressBarStyle not found.

### ISSUE THREAD

**Issue by ghost** [451518849/epub_kitty#10]
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/furkan/.gradle/caches/transforms-2/files-2.1/bf64364ef82cd999d66db3bd84848d01/folioreader-0.5.4/res/layout/progress_dialog.xml:13: AAPT: error: resource android:attr/android:progressBarStyle not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 4s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin epub_kitty...
Running Gradle task 'assembleAarRelease'...

> Configure project :
WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
The current default is 'false'
Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'epub_kitty'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 0s

Exception: The plugin epub_kitty could not be built due to the issue above.

Plugin working ios device,not working android device. what is the problem?

**Comment by ghost** [comment]
then i got such an error.

/Users/furkan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/epub_kitty-0.1.0/android/src/main/java/com/xiaofwang/epub_kitty/Reader.java:6: error: package com.fasterxml.jackson.core.type does not exist
import com.fasterxml.jackson.core.type.TypeReference;
                                      ^
/Users/furkan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/epub_kitty-0.1.0/android/src/main/java/com/xiaofwang/epub_kitty/Reader.java:7: error: package com.fasterxml.jackson.databind does not exist
import com.fasterxml.jackson.databind.ObjectMapper;
                                     ^
/Users/furkan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/epub_kitty-0.1.0/android/src/main/java/com/xiaofwang/epub_kitty/Reader.java:92: error: cannot find symbol
                ObjectMapper objectMapper = new ObjectMapper();
                ^
  symbol: class ObjectMapper
/Users/furkan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/epub_kitty-0.1.0/android/src/main/java/com/xiaofwang/epub_kitty/Reader.java:92: error: cannot find symbol
                ObjectMapper objectMapper = new ObjectMapper();
                                                ^
  symbol: class ObjectMapper
/Users/furkan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/epub_kitty-0.1.0/android/src/main/java/com/xiaofwang/epub_kitty/Reader.java:96: error: cannot find symbol
                            new TypeReference<List<HighlightData>>() {
                                ^
  symbol: class TypeReference
Note: /Users/furkan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/epub_kitty-0.1.0/android/src/main/java/com/xiaofwang/epub_kitty/EpubKittyPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':epub_kitty:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by 451518849** [comment]
it shows com.fasterxml.jackson.core.type does not exist.

**Comment by 451518849** [comment]
Mybe the plugin not installed correctly in android, try to use android studio to load the epub plugin.
