### ISSUE TITLE
iPad halfscreen

### ISSUE THREAD

**Issue by Zehr0** [451518849/epub_kitty#12]
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-03-19 at 08 53 27](https://user-images.githubusercontent.com/38166362/77451546-17af4900-6df5-11ea-984b-9414e4c13d4a.png)

Is there a way to it make full screen?

**Comment by 451518849** [comment]
it's your app setting , not the plugin. Let your app to support iPad device.

**Comment by Zehr0** [comment]
I do not understand.
It runs on iPad fine, just that the reader isn't full screen.
Please can you explain how to implement your solution?

**Comment by 451518849** [comment]
I had test on ipad pro and found this because ipad present default half screen, change the modalPresentationStyle can solve it.

**Comment by Zehr0** [comment]
thanks @451518849 
full screen working now.
![Simulator Screen Shot - iPad Air (3rd generation) - 2020-04-02 at 10 13 30](https://user-images.githubusercontent.com/38166362/78231448-b9582980-74ca-11ea-944f-9a0d3f89473e.png)
