### ISSUE TITLE
App crashes on first read

### ISSUE THREAD

**Issue by obitors** [451518849/epub_kitty#21]
App crashes on first read but works fine on when I re open the app

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.Context.getAssets()' on a null object reference

at com.xiaofwang.epub_kitty.Reader.loadAssetTextAsString(Reader.java:119)
at com.xiaofwang.epub_kitty.Reader.access$100(Reader.java:28)
at com.xiaofwang.epub_kitty.Reader$2.run(Reader.java:95)
at java.lang.Thread.run(Thread.java:919)

**Comment by obitors** [comment]
I have solved it by adding following lines in build.gradle 

buildTypes {
        release {
            signingConfig signingConfigs.debug
            shrinkResources false
            minifyEnabled false
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }

then create a proguard-rules.pro file in app folder and add these lines 

-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

**Comment by Zfinix** [comment]
Wasnt the problem, i found the issue, under Reader. java, the context was set after `getHighlightsAndSave`
![image](https://user-images.githubusercontent.com/25801929/90905127-a5ed2280-e3c7-11ea-8692-c8200d200dbf.png)
but here `getHighlightsAndSave` calls `loadAssetTextAsString` which then calls the context so the context is null
![image](https://user-images.githubusercontent.com/25801929/90905274-d92fb180-e3c7-11ea-9826-12162734b33b.png)
![image](https://user-images.githubusercontent.com/25801929/90905393-067c5f80-e3c8-11ea-83d9-2f9a8e83c087.png)

**Comment by marcqtan** [comment]
it will still crash if you build a RELEASE without passing the --no-shrink option.

> Wasnt the problem, i found the issue, under Reader. java, the context was set after `getHighlightsAndSave`
> ![image](https://user-images.githubusercontent.com/25801929/90905127-a5ed2280-e3c7-11ea-8692-c8200d200dbf.png)
> but here `getHighlightsAndSave` calls `loadAssetTextAsString` which then calls the context so the context is null
> ![image](https://user-images.githubusercontent.com/25801929/90905274-d92fb180-e3c7-11ea-9826-12162734b33b.png)
> ![image](https://user-images.githubusercontent.com/25801929/90905393-067c5f80-e3c8-11ea-83d9-2f9a8e83c087.png)
