### ISSUE TITLE
File is deleted after opening it ones with EpubKitty (iOS, version 0.1.7)

### ISSUE THREAD

**Issue by rharoyan** [451518849/epub_kitty#25]
Hi thanks for the package! Sadly I am having some problems using it. After opening an EPUB file with EpubKitty the file get's deleted from its local path. So I am able to open the book, scroll trough the pages, change the font size etc..., but after closing the book the file is deleted from it's path. This behaviour doesn't accure when I am opening the file with another package. 
I am encountering this behaviour on iOS with 'epub_kitty: ^0.1.7'

I would love to hear some responses.

**Comment by jfunulab** [comment]
@rharoyan which package are you able to successfully use to open epub files apart from this one. `This behaviour doesn't accure when I am opening the file with another package.`

**Comment by saptha** [comment]
In my case I see the file still exists in the same path. But the app crashes with the below error when I try to open the ePub file for the second time. ```

2020-06-30 18:25:22.711345+0530 Magic Author[19991:3176907] [Assert] Cannot be called with asCopy = NO on non-main thread.
2020-06-30 18:25:22.711492+0530 Magic Author[19991:3176907] [Assert] Cannot be called with asCopy = NO on non-main thread.
2020-06-30 18:25:27.006362+0530 Magic Author[19991:3173006] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```
I'm also using a PDF reader and I dont see any issues there while opening the PDF file more than once.

**Comment by saptha** [comment]
Yes, I acknowledge this issue. It was working fine earlier for my iOS app. What I notice is it moves and extracts the original file to its cache folder thereby causing problem for opening it next time.
As a workaround I make a local copy of the original file before giving it to epub_kitty for reading.

**Comment by rharoyan** [comment]
The problem is caused because FolioReaderKit by default deletes the epub after opening. To prevent this behaviour, the platform code in epub_kitty should implement the following line of code: 
`folioReader.presentReader(parentViewController: controller, withEpubPath: path, andConfig: config, **shouldRemoveEpub:false**)`
I have decided to directly implement FolioReaderKit using Flutter platform channels, and have set `shouldRemoveEpub` to `false`
